# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regis.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimediaWidgets import QCameraViewfinder
import os

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        program_dir = os.getcwd()
        object_path = os.path.join(program_dir, "assets/Icon.png")
        Dialog.setObjectName("RegisterStudent")
        Dialog.setWindowIcon(QtGui.QIcon(object_path))
        Dialog.resize(780, 425)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(130, 370, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Abort|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")

        self.viewFinderPage = QtWidgets.QWidget(Dialog)
        self.viewFinderPage.setGeometry(QtCore.QRect(10, 10, 500, 380))
        self.viewFinderPage.setAutoFillBackground(False)
        self.viewFinderPage.setObjectName("viewFinderPage")
        self.cameraSurface = QtWidgets.QLabel(self.viewFinderPage)
        self.cameraSurface.setGeometry(QtCore.QRect(10, 10, 500, 380))
        self.cameraSurface.setText("")
        self.cameraSurface.setObjectName("cameraSurface")

        self.viewFinderPage = QtWidgets.QWidget()
        self.viewFinderPage.setObjectName("viewFinderPage")
        self.viewFinder = QCameraViewfinder(self.viewFinderPage)
        self.viewFinder.setGeometry(QtCore.QRect(10, 10, 500, 380))
        self.viewFinder.setObjectName("viewFinder")

        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(540, 10, 211, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.input_frstnme = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_frstnme.setFont(font)
        self.input_frstnme.setObjectName("input_frstnme")
        self.verticalLayout.addWidget(self.input_frstnme)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.input_mi = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_mi.setFont(font)
        self.input_mi.setObjectName("input_mi")
        self.verticalLayout.addWidget(self.input_mi)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.input_lstnme = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_lstnme.setFont(font)
        self.input_lstnme.setObjectName("input_lstnme")
        self.verticalLayout.addWidget(self.input_lstnme)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input_grlvl = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_grlvl.setFont(font)
        self.input_grlvl.setObjectName("input_grlvl")
        self.verticalLayout.addWidget(self.input_grlvl)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("RegisterStudent", "Register a Student"))
        self.label_4.setText(_translate("RegisterStudent", "First Name*"))
        self.label_3.setText(_translate("RegisterStudent", "Middle Initial"))
        self.label_2.setText(_translate("RegisterStudent", "Last Name*"))
        self.label.setText(_translate("RegisterStudent", "Grade Level*"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
